### ISSUE TITLE
Feedback on mini_ex2 by Marcus Thomas Due Jensen

### ISSUE THREAD

**Issue by duendue** [GustneGustav/Rasmus-er-sej-og-flot#1]
The program displays an array of white squares on a black background. At first, I expected I had to mouse over the squares to trigger an event. However, as soon as I moved the mouse, all the squares started moving around like crazy and changing colour. This illustrates greatly the relation between what you expect would happen and what actually does happen. This shift from expectation to surprise have many parallels to how errors can be perceived by users.

It is somewhat poetic that even though the squares seem to move at random, they are still all fixed to the upper left corner of the canvas, giving the impression of uniformity. Also, the control (or lack thereof) the user has over the movement and colour of the squares also gives an element of orderliness to the program. 

You could consider having the shapes change to other nuances, or having the background change colour as well. You could even go as far as to make the squares turn into say, ellipse, triangles, or something else. All to increase the feeling of “randomness”.

**Comment by LurdKek** [comment]
As Marcus said: Very interesting that the "random" squares are still revolving around the 0,0 mark of the X-Yaxis. I noticed that the speed of the mouse also affects the rigidness of the random placement af the rows of squares. Interesting, and also interesting to see how a drunken mind can affect the process. A good laugh I had (as Yoda would have said). 

Interesting to see how you (I guess) used mapping to determine the random-factor of the square-rows (the bit-art version of a stereotypical gangster-hairstyle?). The rows seem to generate in oppesite direction of that of the mouse.
