### ISSUE TITLE
Quick feedback on mini ex 7 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [GustneGustav/Rasmus-er-sej-og-flot#11]
I have been also wondered about how come many of you like to do the grid in checkbox? Is it something you have discussed together and come up with some kind of ideas about it? 

In relation to the use of objects, perhaps take a look at @MikkelSvendsen piece may help to see the configuration of objects and their attributes?

**Comment by GustneGustav** [comment]
Personally i wanted to make the grid as a way of experimenting with loops, and identifying singular parts of arrays. I discussed it briefly with some of my peers today, and it seems like we all ran into the same problem regarding p5 not identifying all of the checkboxes.
Thanks for the tip, i'll look into it :)
