### ISSUE TITLE
Feedback on miniex8 by Emma Ottilie

### ISSUE THREAD

**Issue by EmmaOttilie** [GustneGustav/Rasmus-er-sej-og-flot#13]
HAPPY BIRTHDAY! You have gained the extreme honour of my feedback as a present. You're welcome. 
I really like your program. I find the simple aesthetic of it really pretty and I think you nailed it with your adding the "mouse follow" function. I would have never even noticed the whole Garfield thing if you had not pointed it out, so you could technically just hurry up and delete it and no one would ever know your shame.

Your thoughts on flowcharts make a lot of sense and I definitely agree that it forces you to think about your code from another perspective.
My only note would be with your input in your flowchart. Isn't there supposed to be a connection from there back to the chart? It seems a bit weird just floating around by itself. 
Kudos and imaginary birthday cakes coming your way. :)

**Comment by GustneGustav** [comment]
I har ret! Jeg er dum. Mit flowchart er utilstrækkeligt. De to stjerne-ting er gensidigt afhængige af hinanden, men det har jeg ikke fået vist ordentligt. Tak for los feedback!
