### ISSUE TITLE
Feedback on mini ex 8 by Emma Pilkington

### ISSUE THREAD

**Issue by Emmapilk** [GustneGustav/Rasmus-er-sej-og-flot#14]
Hi Rasmus.
I think you have made a great choice from the different coding challenges that were presented, as there were so many different to choose between. I like the choice as it's quite easy to understand, and the function with the programme following the mouse is a great idea, and it makes the code more complex and interesting to look at, and interact with. 
As this mini exercise mainly was focused on the flowchart, I'd like this to be my main point in this issue. I think your flowchart is a good simplification of what the programme contains, and is not something only programmers can understand. However your flowchart has a few places where it's confusing, namely because your ''stars moving towards user'' has 2 exiting arrows, which makes it hard to tell the flow of the programme after this point, as well as the ''stars moving according to mouse position''-box having no exiting arrows, which makes it look like the programme will come to a complete stop, which isn't the case here.
Over all i really liked your programme and i thought your modifications had an interesting effect on the visuals and aesthetics of the programme.
Great work Rasmus, I'll see you tomorrow :D :D

**Comment by GustneGustav** [comment]
I har ret! Jeg er dum. Mit flowchart er utilstrækkeligt. De to stjerne-ting er gensidigt afhængige af hinanden, men det har jeg ikke fået vist ordentligt. Tak for los feedback!
